#index:
#    path: /
#    controller: App\Controller\DefaultController::index
recipes_search_form_submit:
    path: /recipes/search
    controller: App\Controller\RecipeController::searchFormSubmit
    methods: [POST]
recipes_search:
    path: /recipes/{query}
    controller: App\Controller\RecipeController::search
    methods: [GET]
